# Generated by Django 4.2.15 on 2025-11-09 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avatars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the conversation', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Conversation title (auto-generated from first message if blank)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether conversation is active or archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when conversation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when conversation was last updated')),
                ('avatar', models.ForeignKey(blank=True, help_text='Avatar used in this conversation (optional, can be text-only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='avatars.avatar')),
                ('user', models.ForeignKey(help_text='User who initiated this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the message', primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Role of who is speaking (user or assistant)', max_length=20)),
                ('sender_type', models.CharField(choices=[('user_input', 'User Input'), ('gemini', 'Gemini API'), ('heygen', 'HeyGen Avatar'), ('system', 'System')], help_text='Which system/source generated this message', max_length=20)),
                ('content', models.TextField(help_text='The actual message content')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON field for storing system-specific data (tokens, video_url, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when message was created')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'), models.Index(fields=['sender_type'], name='messages_sender__1fa575_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='conversatio_user_id_e93dff_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', '-updated_at'], name='conversatio_is_acti_0be388_idx'),
        ),
    ]
