# Generated by Django 4.2.15 on 2025-11-09 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the tier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name: 'free', 'basic', 'pro', 'enterprise'", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Display name for users: 'Free', 'Basic Pro', 'Enterprise'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Tier description shown to users')),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for this tier', max_length=255, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price per billing interval', max_digits=10)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', help_text='Billing interval', max_length=10)),
                ('conversations_per_month', models.IntegerField(default=10, help_text='Maximum conversations per month', validators=[django.core.validators.MinValueValidator(1)])),
                ('video_minutes_per_month', models.IntegerField(default=5, help_text='Maximum video minutes per month (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_concurrent_sessions', models.IntegerField(default=1, help_text='Maximum concurrent sessions', validators=[django.core.validators.MinValueValidator(1)])),
                ('features', models.JSONField(blank=True, default=dict, help_text='Features available in this tier (custom avatars, priority support, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is available for new subscriptions')),
                ('is_featured', models.BooleanField(default=False, help_text='Show this tier prominently')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display tiers (lower first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Tier',
                'verbose_name_plural': 'Subscription Tiers',
                'db_table': 'subscription_tiers',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='subscriptio_is_acti_b20da7_idx'), models.Index(fields=['name'], name='subscriptio_name_cc9211_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for subscription', primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(help_text='Stripe Customer ID', max_length=255, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe Subscription ID for recurring billing', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='active', help_text='Current subscription status', max_length=20)),
                ('current_period_start', models.DateTimeField(help_text='Current billing period start')),
                ('current_period_end', models.DateTimeField(help_text='Current billing period end')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Cancel at end of current period')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When subscription was canceled', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional subscription data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.ForeignKey(help_text='Subscription tier', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptiontier')),
                ('user', models.OneToOneField(help_text='User with this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('conversations_used', models.IntegerField(default=0, help_text='Conversations used this period', validators=[django.core.validators.MinValueValidator(0)])),
                ('video_minutes_used', models.IntegerField(default=0, help_text='Video minutes used this period', validators=[django.core.validators.MinValueValidator(0)])),
                ('period_start', models.DateTimeField(help_text='When current period started')),
                ('period_end', models.DateTimeField(help_text='When current period ends')),
                ('last_reset_at', models.DateTimeField(auto_now=True, help_text='Last time usage was reset')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.OneToOneField(help_text='Associated subscription', on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Usage Limit',
                'verbose_name_plural': 'Usage Limits',
                'db_table': 'usage_limits',
                'indexes': [models.Index(fields=['subscription', 'period_end'], name='usage_limit_subscri_6fadcc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_572d44_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['current_period_end'], name='subscriptio_current_0ac39a_idx'),
        ),
    ]
