# Generated by Django 4.2.15 on 2025-11-16 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='interactive_minutes_per_month',
            field=models.IntegerField(default=1, help_text='Maximum interactive minutes per month (0 = unlimited)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='messages_per_month',
            field=models.IntegerField(default=500, help_text='Maximum messages per month', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='conversations_limit',
            field=models.IntegerField(default=10, help_text='Max conversations this user can have per month (snapshot from tier)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='interactive_minutes_limit',
            field=models.IntegerField(default=1, help_text='Max interactive minutes this user can use per month (0=unlimited, snapshot from tier)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='interactive_minutes_used',
            field=models.IntegerField(default=0, help_text='Interactive minutes used this period', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='max_concurrent_sessions',
            field=models.IntegerField(default=1, help_text='Max concurrent sessions (snapshot from tier)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='messages_limit',
            field=models.IntegerField(default=500, help_text='Max messages this user can send per month (snapshot from tier)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='messages_sent',
            field=models.IntegerField(default=0, help_text='Messages sent this period', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='usagelimit',
            name='video_minutes_limit',
            field=models.IntegerField(default=5, help_text='Max video minutes this user can use per month (0=unlimited, snapshot from tier)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
