# Generated by Django 4.2.15 on 2025-11-09 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_response_time_ms', models.FloatField(default=0.0, help_text='Average API response time in milliseconds')),
                ('error_rate_percent', models.FloatField(default=0.0, help_text='Percentage of failed requests')),
                ('active_users', models.IntegerField(default=0)),
                ('active_conversations', models.IntegerField(default=0)),
                ('database_query_count', models.IntegerField(default=0)),
                ('database_slow_queries', models.IntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('gemini_api_calls', models.IntegerField(default=0)),
                ('stripe_api_calls', models.IntegerField(default=0)),
                ('heygen_api_calls', models.IntegerField(default=0)),
                ('critical_errors', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'System Health',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at'], name='analytics_s_recorde_8d1a77_idx'), models.Index(fields=['error_rate_percent'], name='analytics_s_error_r_a2db96_idx')],
            },
        ),
        migrations.CreateModel(
            name='HourlyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('hour', models.IntegerField(help_text='Hour of day (0-23)')),
                ('active_users', models.IntegerField(default=0)),
                ('api_requests', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('peak_concurrency', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hourly Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_h_timesta_bea553_idx'), models.Index(fields=['hour'], name='analytics_h_hour_c65301_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('conversations_created', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subscriptions_created', models.IntegerField(default=0)),
                ('subscriptions_canceled', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0.0)),
                ('avg_engagement_score', models.FloatField(default=0.0)),
                ('api_errors', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_d_date_0e09df_idx'), models.Index(fields=['new_users'], name='analytics_d_new_use_521ab6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_video_minutes', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('first_conversation_at', models.DateTimeField(blank=True, null=True)),
                ('average_messages_per_conversation', models.FloatField(default=0.0)),
                ('average_conversation_duration_minutes', models.FloatField(default=0.0)),
                ('subscription_tier', models.CharField(default='free', max_length=50)),
                ('subscription_status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Statistics',
                'indexes': [models.Index(fields=['user_id'], name='analytics_u_user_id_77dcab_idx'), models.Index(fields=['subscription_tier'], name='analytics_u_subscri_ef8c8f_idx'), models.Index(fields=['last_active_at'], name='analytics_u_last_ac_ff981a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('churn_risk', models.BooleanField(default=False, help_text='Marked if user likely to churn')),
                ('churn_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_analytics', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Revenue Analytics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'billing_period_start'], name='analytics_r_user_id_067f26_idx'), models.Index(fields=['status', 'created_at'], name='analytics_r_status_859cd4_idx'), models.Index(fields=['churn_risk'], name='analytics_r_churn_r_6038e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('user_signup', 'User Signup'), ('subscription_created', 'Subscription Created'), ('subscription_canceled', 'Subscription Canceled'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('conversation_started', 'Conversation Started'), ('conversation_completed', 'Conversation Completed'), ('api_error', 'API Error'), ('system_error', 'System Error'), ('rate_limit_hit', 'Rate Limit Hit')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='analytics_e_event_t_214f5e_idx'), models.Index(fields=['severity', 'timestamp'], name='analytics_e_severit_e37ffc_idx'), models.Index(fields=['user_id', 'timestamp'], name='analytics_e_user_id_2dcfc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalytic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_count', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('with_gemini', models.BooleanField(default=False)),
                ('with_heygen', models.BooleanField(default=False)),
                ('sentiment_average', models.FloatField(default=0.0, help_text='Average sentiment score (-1 to 1)')),
                ('engagement_score', models.FloatField(default=0.0, help_text='0-100 engagement score')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API'), ('plugin', 'Plugin')], default='web', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytic', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conversation Analytics',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='analytics_c_user_id_7ba724_idx'), models.Index(fields=['with_gemini'], name='analytics_c_with_ge_6b6079_idx'), models.Index(fields=['with_heygen'], name='analytics_c_with_he_f3902f_idx'), models.Index(fields=['created_at'], name='analytics_c_created_dac28b_idx')],
            },
        ),
    ]
