# Generated by Django 4.2.15 on 2025-11-16 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_change', 'Password Changed'), ('password_reset', 'Password Reset'), ('subscription_created', 'Subscription Created'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_downgraded', 'Subscription Downgraded'), ('subscription_canceled', 'Subscription Canceled'), ('subscription_renewed', 'Subscription Renewed'), ('payment_initiated', 'Payment Initiated'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('discount_applied', 'Discount Code Applied'), ('conversation_created', 'Conversation Created'), ('conversation_deleted', 'Conversation Deleted'), ('message_sent', 'Message Sent'), ('resource_accessed', 'Resource Accessed'), ('video_started', 'Video Started'), ('video_completed', 'Video Completed'), ('profile_updated', 'Profile Updated'), ('avatar_uploaded', 'Avatar Uploaded'), ('settings_changed', 'Settings Changed'), ('user_deleted', 'User Deleted (Admin)'), ('user_suspended', 'User Suspended (Admin)'), ('user_restored', 'User Restored (Admin)'), ('tier_created', 'Subscription Tier Created (Admin)'), ('tier_updated', 'Subscription Tier Updated (Admin)'), ('tier_deleted', 'Subscription Tier Deleted (Admin)')], max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('subscription', 'Subscription'), ('payment', 'Payment'), ('conversation', 'Conversation'), ('message', 'Message'), ('avatar', 'Avatar'), ('tier', 'Subscription Tier'), ('discount', 'Discount Code'), ('invoice', 'Invoice'), ('system', 'System')], max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the resource affected', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional JSON metadata')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_abe786_idx'), models.Index(fields=['action', '-created_at'], name='analytics_a_action_8c93de_idx'), models.Index(fields=['resource_type', '-created_at'], name='analytics_a_resourc_d7dab3_idx')],
            },
        ),
    ]
