# Generated by Django 4.2.15 on 2025-09-11 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the avatar', primary_key=True, serialize=False)),
                ('category', models.CharField(help_text="Avatar category (e.g., 'professional', 'casual', 'animated')", max_length=100)),
                ('name', models.CharField(help_text='Display name for the avatar', max_length=255)),
                ('avatar_id', models.CharField(help_text='External avatar ID from HeyGen or similar service', max_length=255, unique=True)),
                ('embed_url', models.TextField(help_text='Full iframe/share URL for embedding the avatar')),
                ('preview_image', models.TextField(help_text="Link to HeyGen's preview image")),
                ('quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Avatar quality setting', max_length=10)),
                ('transparent_background', models.BooleanField(default=False, help_text='Whether avatar has transparent background')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra arbitrary details (tags, description, settings from HeyGen, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this avatar can be used right now')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when avatar was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when avatar was last updated')),
                ('user_id', models.ForeignKey(help_text='The user who owns/created this avatar', on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'db_table': 'avatars',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='avatars_user_id_05148d_idx'), models.Index(fields=['category', 'is_active'], name='avatars_categor_c994d0_idx'), models.Index(fields=['created_at'], name='avatars_created_9a4f40_idx')],
            },
        ),
    ]
