# Generated by Django 4.2.15 on 2025-11-09 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Discount code (e.g., 'SAVE20', 'SUMMER50')", max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Description of the discount', max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], help_text='Type of discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage 0-100 or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum times this code can be used (null = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times used', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_uses_per_user', models.IntegerField(default=1, help_text='Maximum times a single user can use this code', validators=[django.core.validators.MinValueValidator(1)])),
                ('valid_from', models.DateTimeField(help_text='When discount becomes active')),
                ('valid_until', models.DateTimeField(help_text='When discount expires')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', help_text='Discount status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_tiers', models.ManyToManyField(blank=True, help_text='Tiers this discount applies to (leave empty for all)', related_name='discounts', to='subscriptions.subscriptiontier')),
                ('created_by', models.ForeignKey(help_text='Admin who created this discount', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'discounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe PaymentIntent ID', max_length=255, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original amount before discount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Final amount charged (original - discount)', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', help_text='Payment status', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(blank=True, help_text='Discount code used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.discount')),
                ('subscription', models.ForeignKey(blank=True, help_text='Associated subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(help_text='User making payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(help_text='Stripe Invoice ID', max_length=255, unique=True)),
                ('invoice_number', models.CharField(help_text='Invoice number for display', max_length=50, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original amount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount applied', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount due', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('issue_date', models.DateField(help_text='When invoice was issued')),
                ('due_date', models.DateField(help_text='When payment is due')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was received', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('uncollectible', 'Uncollectible'), ('void', 'Void')], default='open', help_text='Invoice status', max_length=20)),
                ('pdf_url', models.URLField(blank=True, help_text='URL to invoice PDF', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(blank=True, help_text='Associated payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='payments.payment')),
                ('subscription', models.ForeignKey(blank=True, help_text='Associated subscription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.subscription')),
                ('user', models.ForeignKey(help_text='User invoice is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='payments.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Usage',
                'verbose_name_plural': 'Discount Usages',
                'db_table': 'discount_usages',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_id_1b771c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_status_426d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_stripe__6cb0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['user', 'status'], name='invoices_user_id_9940be_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stripe_invoice_id'], name='invoices_stripe__83e0c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discountusage',
            unique_together={('discount', 'user')},
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code', 'status'], name='discounts_code_7576e8_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['status', 'valid_until'], name='discounts_status_d2353f_idx'),
        ),
    ]
